package:
    name: pycwr
    version: 0.2

build:
    skip: True # [py<35]

source:
    git_url: https://github.com/YvZheng/pycwr.git

requirements:
    build:
       - python

    host:
       - python
       - setuptools

    run:
        - 'python >=3.6*'
        - 'numpy <=1.15.0'
        - 'scipy >=1.1.0'
        - 'matplotlib >=2.2.3'
        - 'netcdf4 >=1.5.3'
        - 'cartopy >=0.17*'
        - 'pandas >=0.23.4'
        - 'easydict >=1.9'
        - 'pyproj >=1.9.6'
        - 'xarray >=0.13*'
        - 'pyqt >=5.10*'

about:
    home: https://github.com/YvZheng/pycwr
    description: 
    license: MIT
    license_file: LICENSE.txt
